import { Destination, Template } from './types';

export const DESTINATIONS: Destination[] = [
  // --- BELITUNG ISLAND ---
  {
    id: 'tanjung-tinggi',
    name: 'Pantai Tanjung Tinggi',
    location: 'Sijuk, Belitung',
    region: 'Belitung Island',
    subLocation: 'Belitung',
    categories: ['Beach', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2–3 hours',
    rating: 4.8,
    reviews: 1247,
    emoji: '🏖',
    description: 'Iconic granite-boulder beach made famous by the film Laskar Pelangi. Crystal-clear turquoise water.',
    tips: ['Visit before 8am for the best light', 'Bring snorkeling gear'],
    bestFor: ['Couples', 'Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1544971587-b842c27f8e14?auto=format&fit=crop&q=80&w=800',
    latitude: -2.7163,
    longitude: 107.7214
  },
  {
    id: 'lengkuas-island',
    name: 'Pulau Lengkuas',
    location: 'Sijuk, Belitung',
    region: 'Belitung Island',
    subLocation: 'Belitung',
    categories: ['Beach', 'Nature', 'Photo Spot'],
    entryFee: 'Boat Rp 500k-800k',
    priceValue: 500000,
    duration: '4-6 hours',
    rating: 4.9,
    reviews: 3500,
    emoji: '🗼',
    description: 'Historic Dutch lighthouse from 1882 surrounded by crystal clear waters and coral gardens.',
    tips: ['Climb the lighthouse for panoramic views', 'Great for snorkeling'],
    bestFor: ['Everyone'],
    imageUrl: 'https://images.unsplash.com/photo-1516641295413-435fa52cc596?auto=format&fit=crop&q=80&w=800',
    latitude: -2.5354,
    longitude: 107.6214
  },
  {
    id: 'tanjung-pendam',
    name: 'Pantai Tanjung Pendam',
    location: 'Tanjung Pandan, Belitung',
    region: 'Belitung Island',
    subLocation: 'Belitung',
    categories: ['Beach', 'Photo Spot'],
    entryFee: 'Rp 5,000',
    priceValue: 5000,
    duration: '1-2 hours',
    rating: 4.4,
    reviews: 1800,
    emoji: '🌆',
    description: 'The social hub of Tanjung Pandan. Perfect for sunset walks and local street food.',
    tips: ['Great for people-watching at sunset', 'Try the local snacks'],
    bestFor: ['Families', 'Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    latitude: -2.73,
    longitude: 107.62
  },
  {
    id: 'kopi-amien',
    name: 'Kopi Amien',
    location: 'Tanjung Pandan, Belitung',
    region: 'Belitung Island',
    subLocation: 'Belitung',
    categories: ['Cafe'],
    entryFee: 'Rp 15k-40k',
    priceValue: 25000,
    duration: '1 hour',
    rating: 4.7,
    reviews: 560,
    emoji: '☕',
    description: 'A classic Belitung coffee experience with a more modern touch than Kong Djie.',
    tips: ['Try the butter coffee', 'Good WiFi for remote work'],
    bestFor: ['Solo', 'Couples'],
    imageUrl: 'https://images.unsplash.com/photo-1501339818192-38aef724fce4?auto=format&fit=crop&q=80&w=800',
    latitude: -2.74,
    longitude: 107.64
  },
  {
    id: 'belitung-traditional-house',
    name: 'Rumah Adat Belitung',
    location: 'Tanjung Pandan, Belitung',
    region: 'Belitung Island',
    subLocation: 'Belitung',
    categories: ['Culture'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1 hour',
    rating: 4.6,
    reviews: 430,
    emoji: '🏠',
    description: 'Beautiful traditional Malay-style house showcasing local architecture and artifacts.',
    tips: ['Great for understanding local heritage', 'Respect local customs when entering'],
    bestFor: ['Culture Lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    latitude: -2.735,
    longitude: 107.635
  },
  {
    id: 'kong-djie',
    name: 'Warung Kopi Kong Djie',
    location: 'Tanjung Pandan, Belitung',
    region: 'Belitung Island',
    subLocation: 'Belitung',
    categories: ['Cafe', 'Culture'],
    entryFee: 'Rp 10,000–30,000',
    priceValue: 20000,
    duration: '1–2 hours',
    rating: 4.9,
    reviews: 2108,
    emoji: '☕',
    description: "Belitung's most legendary coffee shop since 1943. Thick black coffee in traditional glass.",
    tips: ['Peak hours 7–9am', 'Arrive early for authentic atmosphere'],
    bestFor: ['Couples', 'Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1501339818192-38aef724fce4?auto=format&fit=crop&q=80&w=800',
    latitude: -2.7303,
    longitude: 107.6322
  },
  {
    id: 'mie-atep',
    name: 'Mie Belitung Atep',
    location: 'Tanjung Pandan, Belitung',
    region: 'Belitung Island',
    subLocation: 'Belitung',
    categories: ['Food'],
    entryFee: 'Rp 28,000',
    priceValue: 28000,
    duration: '1 hour',
    rating: 4.8,
    reviews: 2344,
    emoji: '🍜',
    description: 'The most famous Mie Belitung restaurant, serving since 1973.',
    tips: ['Queue after 11am — arrive at 10:30am to beat it'],
    bestFor: ['Everyone'],
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800',
    latitude: -2.7305,
    longitude: 107.6342
  },
  {
    id: 'museum-kata',
    name: 'Museum Kata Andrea Hirata',
    location: 'Gantung, East Belitung',
    region: 'Belitung Island',
    subLocation: 'East Belitung',
    categories: ['Culture', 'Photo Spot'],
    entryFee: 'Rp 50,000',
    priceValue: 50000,
    duration: '1.5–2 hours',
    rating: 4.7,
    reviews: 1503,
    emoji: '📚',
    description: 'Colorful literary museum by the author of Laskar Pelangi.',
    tips: ['Premium access includes a small coffee', 'Great for photos'],
    bestFor: ['Couples', 'Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=800',
    latitude: -3.0039,
    longitude: 108.1568
  },
  {
    id: 'danau-kaolin-belitung',
    name: 'Danau Kaolin Belitung',
    location: 'Tanjung Pandan, Belitung',
    region: 'Belitung Island',
    subLocation: 'Belitung',
    categories: ['Nature', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1 hour',
    rating: 4.6,
    reviews: 890,
    emoji: '💎',
    description: 'Turquoise water against white kaolin hills. Surreal landscape.',
    tips: ['Best color at midday', 'Wear sunblock'],
    bestFor: ['Solo', 'Couples'],
    imageUrl: 'https://images.unsplash.com/photo-1433086566608-0b91232845c4?auto=format&fit=crop&q=80&w=800',
    latitude: -2.7667,
    longitude: 107.6534
  },
  {
    id: 'vihara-kwan-im-belitung',
    name: 'Vihara Dewi Kwan Im',
    location: 'Damar, East Belitung',
    region: 'Belitung Island',
    subLocation: 'East Belitung',
    categories: ['Culture', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1 hour',
    rating: 4.7,
    reviews: 450,
    emoji: '🏮',
    description: 'Historic temple on a hill with a view of Burung Mandi Beach.',
    tips: ['Visit at sunrise for spectacular views'],
    bestFor: ['Solo', 'Culture Lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&q=80&w=800',
    latitude: -2.8543,
    longitude: 108.2256
  },
  {
    id: 'pantai-burung-mandi',
    name: 'Pantai Burung Mandi',
    location: 'Damar, East Belitung',
    region: 'Belitung Island',
    subLocation: 'East Belitung',
    categories: ['Beach', 'Nature'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2 hours',
    rating: 4.5,
    reviews: 800,
    emoji: '🐦',
    description: 'Beach with colorful traditional fishing boats (Catering). Very picturesque.',
    tips: ['Great for morning walks', 'Local snacks available'],
    bestFor: ['Families'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    latitude: -2.8643,
    longitude: 108.2356
  },
  {
    id: 'kopi-manggar',
    name: 'Warung Kopi Manggar',
    location: 'Manggar, East Belitung',
    region: 'Belitung Island',
    subLocation: 'East Belitung',
    categories: ['Cafe', 'Culture'],
    entryFee: 'Rp 10k-25k',
    priceValue: 15000,
    duration: '1 hour',
    rating: 4.6,
    reviews: 1200,
    emoji: '🏘',
    description: 'Manggar is known as the city of 1000 coffee shops. Authentic vibes.',
    tips: ['Try the signature coffee or milk coffee'],
    bestFor: ['Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1501339818192-38aef724fce4?auto=format&fit=crop&q=80&w=800',
    latitude: -2.8843,
    longitude: 108.2656
  },
  {
    id: 'open-pit-nam-salu',
    name: 'Open Pit Nam Salu',
    location: 'Kelapa Kampit, East Belitung',
    region: 'Belitung Island',
    subLocation: 'East Belitung',
    categories: ['Nature', 'Photo Spot'],
    entryFee: 'Rp 20,000',
    priceValue: 20000,
    duration: '2 hours',
    rating: 4.7,
    reviews: 600,
    emoji: '🕳',
    description: 'Former deep-tin mining site with a stunning turquoise lake inside a crater.',
    tips: ['Guided tours are available', 'Wear comfortable trekking shoes'],
    bestFor: ['Adventure Seekers'],
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
    latitude: -2.7143,
    longitude: 108.0656
  },
  {
    id: 'pantai-serdang',
    name: 'Pantai Serdang',
    location: 'Manggar, East Belitung',
    region: 'Belitung Island',
    subLocation: 'East Belitung',
    categories: ['Beach'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2 hours',
    rating: 4.5,
    reviews: 800,
    emoji: '🏖',
    description: 'Beautiful white sand beach in Manggar, the city of 1001 coffee shops.',
    tips: ['Visit in the morning for the best breeze', 'Try coffee nearby'],
    bestFor: ['Families', 'Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    latitude: -2.88,
    longitude: 108.28
  },
  {
    id: 'kelam-hill',
    name: 'Bukit Kelam Belitung',
    location: 'Kelapa Kampit, East Belitung',
    region: 'Belitung Island',
    subLocation: 'East Belitung',
    categories: ['Nature', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2 hours',
    rating: 4.4,
    reviews: 150,
    emoji: '⛰',
    description: 'A massive granite monolith offering trekking trails and panoramic inland views.',
    tips: ['Carry water, it can get humid', 'Best visited early morning'],
    bestFor: ['Adventure Seekers'],
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
    latitude: -2.7,
    longitude: 108.05
  },

  // --- BANGKA ISLAND ---
  {
    id: 'tiam-o-ie',
    name: 'Kopi Tradisional Tiam O Ie',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Cafe', 'Culture'],
    entryFee: 'Rp 10,000–25,000',
    priceValue: 15000,
    duration: '1 hour',
    rating: 4.7,
    reviews: 673,
    emoji: '🍳',
    description: 'Authentic traditional Bangka kopitiam with old-school atmosphere.',
    tips: ['Try the half-boiled eggs and local bread'],
    bestFor: ['Solo', 'Culture lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=800',
    latitude: -2.1244,
    longitude: 106.1133
  },
  {
    id: 'martabak-acau',
    name: 'Martabak Acau 89',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Food'],
    entryFee: 'Rp 40,000–90,000',
    priceValue: 60000,
    duration: '30 min',
    rating: 4.8,
    reviews: 1500,
    emoji: '🥙',
    description: 'The real Bangka Martabak experience. Sweet or savory, both legendary.',
    tips: ['Opens late afternoon', 'Expect a queue'],
    bestFor: ['Everyone'],
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800',
    latitude: -2.1266,
    longitude: 106.1155
  },
  {
    id: 'pantai-pasir-padi',
    name: 'Pantai Pasir Padi',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Beach'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2 hours',
    rating: 4.4,
    reviews: 2500,
    emoji: '⛱',
    description: 'Closest beach to Pangkalpinang city center. Great for seafood and morning runs.',
    tips: ['Try the local seafood stalls along the shore'],
    bestFor: ['Families'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    latitude: -2.1643,
    longitude: 106.1633
  },
  {
    id: 'bbg-bangka',
    name: 'Bangka Botanical Garden',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Nature', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1.5 hours',
    rating: 4.5,
    reviews: 1800,
    emoji: '🌲',
    description: 'Lush greenery and pine trees. A refreshing escape from city life.',
    tips: ['Great for morning cycling', 'Photo spots with pine backgrounds'],
    bestFor: ['Nature Lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1501183638710-841dd1904538?auto=format&fit=crop&q=80&w=800',
    latitude: -2.1143,
    longitude: 106.1533
  },
  {
    id: 'museum-timah-indonesia',
    name: 'Museum Timah Indonesia',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Culture'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1.5 hours',
    rating: 4.6,
    reviews: 1200,
    emoji: '🏛',
    description: 'The only tin museum in Asia, located in a heritage building in Pangkalpinang.',
    tips: ['Learn about the history of Bangka tin', 'Great for students and curious minds'],
    bestFor: ['Culture lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1503174971373-b1f69850bdf3?auto=format&fit=crop&q=80&w=800',
    latitude: -2.12,
    longitude: 106.11
  },
  {
    id: 'jembatan-emas',
    name: 'Jembatan Emas',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1 hour',
    rating: 4.5,
    reviews: 900,
    emoji: '🌉',
    description: 'Iconic bascule bridge in Bangka, perfect for evening photos.',
    tips: ['Visit at night for the lights', 'Check the schedule for bridge opening'],
    bestFor: ['Photo lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1513584684374-8bdb74838a0f?auto=format&fit=crop&q=80&w=800',
    latitude: -2.15,
    longitude: 106.18
  },
  {
    id: 'kopi-es-tak-kie-pkp',
    name: 'Kopi Es Tak Kie Bangka',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Cafe', 'Food'],
    entryFee: 'Rp 20k-50k',
    priceValue: 35000,
    duration: '1 hour',
    rating: 4.6,
    reviews: 420,
    emoji: '☕',
    description: 'A branch of the legendary Glodok coffee shop, offering a nostalgic vibe in Pangkalpinang.',
    tips: ['Try their signature iced coffee', 'Great for a morning break'],
    bestFor: ['Solo', 'Couples'],
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=800',
    latitude: -2.12,
    longitude: 106.11
  },
  {
    id: 'otako-amui',
    name: 'Otak-otak Amui',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Food'],
    entryFee: 'Rp 3k-5k / piece',
    priceValue: 30000,
    duration: '1 hour',
    rating: 4.8,
    reviews: 1500,
    emoji: '🍢',
    description: 'Famous grilled fish cake with spicy peanut or bean sauce. A must-try snack.',
    tips: ['Eat it while it\'s hot', 'Try all three different sauces'],
    bestFor: ['Foodies'],
    imageUrl: 'https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?auto=format&fit=crop&q=80&w=800',
    latitude: -2.125,
    longitude: 106.115
  },
  {
    id: 'warkop-akew-sungailiat',
    name: 'Warkop Akew Sungailiat',
    location: 'Sungailiat, Bangka',
    region: 'Bangka Island',
    subLocation: 'Bangka',
    categories: ['Cafe'],
    entryFee: 'Rp 10k-30k',
    priceValue: 20000,
    duration: '1 hour',
    rating: 4.5,
    reviews: 350,
    emoji: '☕',
    description: 'Traditional coffee shop in Sungailiat known for its local coffee and toast.',
    tips: ['Popular spot for morning coffee', 'Try the Half-boiled eggs'],
    bestFor: ['Solo', 'Locals'],
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=800',
    latitude: -1.86,
    longitude: 106.12
  },
  {
    id: 'mie-koba-sungailiat',
    name: 'Mie Koba Sungailiat',
    location: 'Sungailiat, Bangka',
    region: 'Bangka Island',
    subLocation: 'Bangka',
    categories: ['Food'],
    entryFee: 'Rp 20k-40k',
    priceValue: 25000,
    duration: '1 hour',
    rating: 4.7,
    reviews: 680,
    emoji: '🍜',
    description: 'Savory fish-based noodle soup with hard-boiled eggs and bean sprouts.',
    tips: ['Add extra lime for better flavor', 'Best enjoyed for lunch'],
    bestFor: ['Foodies'],
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800',
    latitude: -1.85,
    longitude: 106.11
  },
  {
    id: 'pantai-tikus-emas',
    name: 'Pantai Tikus Emas',
    location: 'Sungailiat, Bangka',
    region: 'Bangka Island',
    subLocation: 'Bangka',
    categories: ['Beach', 'Photo Spot'],
    entryFee: 'Rp 5,000',
    priceValue: 5000,
    duration: '2-3 hours',
    rating: 4.7,
    reviews: 1200,
    emoji: '🐀',
    description: 'Popular beach with a large golden rat statue. Family favorite.',
    tips: ['Great for kids with many activities', 'Don\'t miss the golden rat statue photo'],
    bestFor: ['Families'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    latitude: -1.88,
    longitude: 106.13
  },
  {
    id: 'pagoda-nusantara',
    name: 'Pagoda Nusantara',
    location: 'Sungailiat, Bangka',
    region: 'Bangka Island',
    subLocation: 'Bangka',
    categories: ['Culture', 'Photo Spot'],
    entryFee: 'Rp 10,000',
    priceValue: 10000,
    duration: '1 hour',
    rating: 4.6,
    reviews: 450,
    emoji: '🏮',
    description: 'A beautiful pagoda on a hill with a commanding view of the surrounding forests and sea.',
    tips: ['Great for sunset viewing', 'Respect the religious site'],
    bestFor: ['Culture lovers', 'Photo lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&q=80&w=800',
    latitude: -1.84,
    longitude: 106.11
  },
  {
    id: 'pantai-matras',
    name: 'Pantai Matras',
    location: 'Sungailiat, Bangka',
    region: 'Bangka Island',
    subLocation: 'Bangka',
    categories: ['Beach'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2 hours',
    rating: 4.3,
    reviews: 508,
    emoji: '🌴',
    description: 'Longest beach in Bangka, popular for weekend picnics.',
    tips: ['Weekday visits are more peaceful'],
    bestFor: ['Family', 'Groups'],
    imageUrl: 'https://images.unsplash.com/photo-1520483601560-389dff434f1c?auto=format&fit=crop&q=80&w=800',
    latitude: -1.8654,
    longitude: 106.1245
  },
  {
    id: 'vihara-puri-tri-agung',
    name: 'Vihara Puri Tri Agung',
    location: 'Sungailiat, Bangka',
    region: 'Bangka Island',
    subLocation: 'Bangka',
    categories: ['Culture', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1.5 hours',
    rating: 4.7,
    reviews: 890,
    emoji: '🕍',
    description: 'Majestic temple overlooking the sea. Stunning architecture.',
    tips: ['Visit at sunset for the best view of the ocean'],
    bestFor: ['Solo', 'Couples'],
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    latitude: -1.85,
    longitude: 106.12
  },
  {
    id: 'delocomotief',
    name: 'DeLocomotief',
    location: 'Sungailiat, Bangka',
    region: 'Bangka Island',
    subLocation: 'Bangka',
    categories: ['Beach', 'Cafe', 'Photo Spot'],
    entryFee: 'Rp 25,000',
    priceValue: 25000,
    duration: '2-3 hours',
    rating: 4.6,
    reviews: 1400,
    emoji: '🚂',
    description: 'Beach cafe and art spot with historic locomotive themes.',
    tips: ['Visit in the afternoon for sunset vibes'],
    bestFor: ['Couples', 'Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=800',
    latitude: -1.82,
    longitude: 106.14
  },
  {
    id: 'bukit-menumbing',
    name: 'Pesanggrahan Menumbing',
    location: 'Muntok, West Bangka',
    region: 'Bangka Island',
    subLocation: 'West Bangka',
    categories: ['Culture', 'Nature', 'Photo Spot'],
    entryFee: 'Rp 10,000',
    priceValue: 10000,
    duration: '2 hours',
    rating: 4.6,
    reviews: 320,
    emoji: '🏰',
    description: 'Historic hilltop guesthouse where Indonesian leaders were exiled.',
    tips: ['Cooler temperature here', 'Bring a jacket'],
    bestFor: ['Solo', 'History Buffs'],
    imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=800',
    latitude: -1.98,
    longitude: 105.17
  },
  {
    id: 'tanjung-kalian',
    name: 'Mercusuar Tanjung Kalian',
    location: 'Muntok, West Bangka',
    region: 'Bangka Island',
    subLocation: 'West Bangka',
    categories: ['Beach', 'Culture'],
    entryFee: 'Rp 5,000',
    priceValue: 5000,
    duration: '1.5 hours',
    rating: 4.5,
    reviews: 600,
    emoji: '🚨',
    description: 'Historic Dutch lighthouse from 1862. Important landmark in Bangka.',
    tips: ['Climb to the top for coastal views'],
    bestFor: ['Culture lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1516641295413-435fa52cc596?auto=format&fit=crop&q=80&w=800',
    latitude: -2.01,
    longitude: 105.14
  },
  {
    id: 'danau-kaolin-air-bara',
    name: 'Danau Kaolin Air Bara',
    location: 'Air Bara, South Bangka',
    region: 'Bangka Island',
    subLocation: 'South Bangka',
    categories: ['Nature', 'Photo Spot'],
    entryFee: 'Rp 5,000',
    priceValue: 5000,
    duration: '1 hour',
    rating: 4.5,
    reviews: 560,
    emoji: '💧',
    description: 'Famous blue and green lakes formed from former mining sites.',
    tips: ['Great for photography drones'],
    bestFor: ['Photo lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&q=80&w=800',
    latitude: -2.5,
    longitude: 106.2
  },
  {
    id: 'benteng-toboali',
    name: 'Benteng Toboali',
    location: 'Toboali, South Bangka',
    region: 'Bangka Island',
    subLocation: 'South Bangka',
    categories: ['Culture', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1 hour',
    rating: 4.2,
    reviews: 300,
    emoji: '🏗',
    description: 'Ruins of a Dutch colonial fort from 1825. Overgrown by banyan trees.',
    tips: ['Very eerie and beautiful photo spots'],
    bestFor: ['Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&q=80&w=800',
    latitude: -3.01,
    longitude: 106.45
  },
  {
    id: 'pantai-tanjung-berikat',
    name: 'Pantai Tanjung Berikat',
    location: 'Central Bangka',
    region: 'Bangka Island',
    subLocation: 'Central Bangka',
    categories: ['Beach', 'Nature'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2 hours',
    rating: 4.4,
    reviews: 120,
    emoji: '🌊',
    description: 'Pristine beach with a lighthouse and rocky shores.',
    tips: ['Remote location, bring your own food'],
    bestFor: ['Adventure seekers'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    latitude: -2.3,
    longitude: 106.7
  },
  {
    id: 'mie-koba',
    name: 'Mie Koba Iskandar',
    location: 'Koba, Central Bangka',
    region: 'Bangka Island',
    subLocation: 'Central Bangka',
    categories: ['Food'],
    entryFee: 'Rp 20,000',
    priceValue: 20000,
    duration: '1 hour',
    rating: 4.8,
    reviews: 1600,
    emoji: '🍛',
    description: 'Bangka signature fish noodle soup with a rich, savory broth.',
    tips: ['Try with extra sambal if you like heat'],
    bestFor: ['Everyone'],
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800',
    latitude: -2.48,
    longitude: 106.2
  },
  {
    id: 'batu-belimbing-toboali',
    name: 'Batu Belimbing Toboali',
    location: 'Toboali, South Bangka',
    region: 'Bangka Island',
    subLocation: 'South Bangka',
    categories: ['Nature', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1 hour',
    rating: 4.6,
    reviews: 400,
    emoji: '🗿',
    description: 'Unique rock formations that resemble a starfruit (belimbing). Natural wonder.',
    tips: ['Best viewed in the afternoon', 'Very close to Toboali city'],
    bestFor: ['Families', 'Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1544971587-b842c27f8e14?auto=format&fit=crop&q=80&w=800',
    latitude: -3.02,
    longitude: 106.46
  },
  {
    id: 'otak-otak-toboali',
    name: 'Otak-otak Toboali "Asien"',
    location: 'Toboali, South Bangka',
    region: 'Bangka Island',
    subLocation: 'South Bangka',
    categories: ['Food'],
    entryFee: 'Rp 20,000–50,000',
    priceValue: 35000,
    duration: '45 min',
    rating: 4.7,
    reviews: 800,
    emoji: '🍡',
    description: 'Famous grilled fish cakes with spicy bean sauce. A South Bangka staple.',
    tips: ['Eat them while hot', 'Buy some as souvenirs'],
    bestFor: ['Foodies'],
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800',
    latitude: -3.015,
    longitude: 106.455
  },
  {
    id: 'hutan-mangrove-kurau',
    name: 'Hutan Mangrove Kurau',
    location: 'Kurau, Central Bangka',
    region: 'Bangka Island',
    subLocation: 'Central Bangka',
    categories: ['Nature', 'Photo Spot'],
    entryFee: 'Rp 10,000',
    priceValue: 10000,
    duration: '2 hours',
    rating: 4.5,
    reviews: 350,
    emoji: '🛶',
    description: 'Boat tour through dense mangrove forests. Peaceful and biodiverse.',
    tips: ['Rent a boat for the full experience', 'Great for bird watching'],
    bestFor: ['Nature Lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1501183638710-841dd1904538?auto=format&fit=crop&q=80&w=800',
    latitude: -2.35,
    longitude: 106.22
  },
  {
    id: 'museum-timah-muntok',
    name: 'Museum Timah Muntok',
    location: 'Muntok, West Bangka',
    region: 'Bangka Island',
    subLocation: 'West Bangka',
    categories: ['Culture'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1.5 hours',
    rating: 4.6,
    reviews: 450,
    emoji: '⛏',
    description: 'Museum detailing the history of tin mining in Bangka and Muntok.',
    tips: ['Look for the telegraph room', 'History of WW2 is also here'],
    bestFor: ['Culture lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    latitude: -2.06,
    longitude: 105.15
  },
  {
    id: 'laskar-pelangi-school',
    name: 'Replika SD Muhammadiyah (Laskar Pelangi)',
    location: 'Gantung, East Belitung',
    region: 'Belitung Island',
    subLocation: 'East Belitung',
    categories: ['Culture', 'Photo Spot'],
    entryFee: 'Rp 5,000',
    priceValue: 5000,
    duration: '1 hour',
    rating: 4.8,
    reviews: 2100,
    emoji: '🏫',
    description: 'The iconic school replica from the Laskar Pelangi movie, symbolizing Belitung\'s educational spirit.',
    tips: ['Visit the Word Museum nearby', 'Great for nostalgic photos'],
    bestFor: ['Families', 'Culture Lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1544971587-b842c27f8e14?auto=format&fit=crop&q=80&w=800',
    latitude: -3.0035,
    longitude: 108.156
  },
  {
    id: 'pantai-tanjung-tinggi-granite',
    name: 'Batu Granit Raksasa',
    location: 'Sijuk, Belitung',
    region: 'Belitung Island',
    subLocation: 'Belitung',
    categories: ['Nature', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2 hours',
    rating: 4.9,
    reviews: 3200,
    emoji: '🪨',
    description: 'Legendary giant granite rock formations that defined Belitung\'s coastal landscape.',
    tips: ['Climb carefully for sunset views', 'Iconic movie location'],
    bestFor: ['Everyone'],
    imageUrl: 'https://images.unsplash.com/photo-1544971587-b842c27f8e14?auto=format&fit=crop&q=80&w=800',
    latitude: -2.716,
    longitude: 107.721
  },
  {
    id: 'tung-tau-coffee',
    name: 'Warung Kopi Tung Tau',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Cafe', 'Food'],
    entryFee: 'Rp 15k-40k',
    priceValue: 25000,
    duration: '1 hour',
    rating: 4.7,
    reviews: 1800,
    emoji: '☕',
    description: 'Local legend serving authentic coffee and their signature "roti panggang" (toast) since 1938.',
    tips: ['Try the charcoal-grilled toast', 'Great for breakfast'],
    bestFor: ['Solo', 'Locals'],
    imageUrl: 'https://images.unsplash.com/photo-1501339818192-38aef724fce4?auto=format&fit=crop&q=80&w=800',
    latitude: -2.122,
    longitude: 106.11
  },
  {
    id: 'sentosa-cemetery',
    name: 'Pekuburan Sentosa',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Culture', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1 hour',
    rating: 4.5,
    reviews: 540,
    emoji: '🪦',
    description: 'The largest Chinese cemetery in Southeast Asia, known for its grand tombs and cultural significance.',
    tips: ['Visit during Cheng Beng festival for full atmosphere', 'Best in early morning'],
    bestFor: ['History Buffs'],
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&q=80&w=800',
    latitude: -2.13,
    longitude: 106.12
  },
  {
    id: 'gebong-memarong',
    name: 'Desa Tradisional Gebong Memarong',
    location: 'Air Anyir, Bangka',
    region: 'Bangka Island',
    subLocation: 'Bangka',
    categories: ['Culture'],
    entryFee: 'Rp 10k',
    priceValue: 10000,
    duration: '1.5 hours',
    rating: 4.6,
    reviews: 210,
    emoji: '🛖',
    description: 'Traditional Mapur tribe village showcasing authentic Bangka stilt houses.',
    tips: ['Learn about local weaving', 'Taste the Mapur tribe snacks'],
    bestFor: ['Culture lovers'],
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    latitude: -1.95,
    longitude: 106.2
  },
  {
    id: 'pantai-terentang',
    name: 'Pantai Terentang',
    location: 'Koba, Central Bangka',
    region: 'Bangka Island',
    subLocation: 'Central Bangka',
    categories: ['Beach', 'Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2 hours',
    rating: 4.4,
    reviews: 320,
    emoji: '🏖',
    description: 'A long stretch of beach in Central Bangka, perfect for a relaxing stroll.',
    tips: ['Great for kite flying', 'Local snacks available nearby'],
    bestFor: ['Families'],
    imageUrl: 'https://images.unsplash.com/photo-1544971587-b842c27f8e14?auto=format&fit=crop&q=80&w=800',
    latitude: -2.48,
    longitude: 106.32
  },
  {
    id: 'mie-koba-asli',
    name: 'Mie Koba Asli',
    location: 'Koba, Central Bangka',
    region: 'Bangka Island',
    subLocation: 'Central Bangka',
    categories: ['Food'],
    entryFee: 'Rp 20k-40k',
    priceValue: 25000,
    duration: '45 min',
    rating: 4.8,
    reviews: 890,
    emoji: '🍜',
    description: 'The original location of the famous Mie Koba. A culinary landmark.',
    tips: ['The broth is rich in fish flavor', 'A must-visit when in Koba'],
    bestFor: ['Foodies'],
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800',
    latitude: -2.49,
    longitude: 106.2
  },
  {
    id: 'pantai-nek-aji',
    name: 'Pantai Nek Aji',
    location: 'Toboali, South Bangka',
    region: 'Bangka Island',
    subLocation: 'South Bangka',
    categories: ['Beach'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '1 hour',
    rating: 4.2,
    reviews: 120,
    emoji: '🏖',
    description: 'Local beach in Toboali, central to community events and evening hangouts.',
    tips: ['Great for people-watching', 'Try the street food nearby'],
    bestFor: ['Solo', 'Locals'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    latitude: -3.015,
    longitude: 106.445
  },
  {
    id: 'mayor-china-house',
    name: 'Mayor China House',
    location: 'Muntok, West Bangka',
    region: 'Bangka Island',
    subLocation: 'West Bangka',
    categories: ['Culture', 'Photo Spot'],
    entryFee: 'Rp 5,000',
    priceValue: 5000,
    duration: '1 hour',
    rating: 4.5,
    reviews: 210,
    emoji: '🏮',
    description: 'Historical mansion of the Chinese Mayor in Muntok, showcasing Peranakan architecture.',
    tips: ['Great for vintage photography', 'Learn about the local Peranakan history'],
    bestFor: ['History Buffs'],
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&q=80&w=800',
    latitude: -2.065,
    longitude: 105.155
  },
  {
    id: 'pulau-ketawai',
    name: 'Pulau Ketawai',
    location: 'Kurau, Central Bangka',
    region: 'Bangka Island',
    subLocation: 'Central Bangka',
    categories: ['Beach', 'Nature', 'Photo Spot'],
    entryFee: 'Boat Rp 300k-500k',
    priceValue: 400000,
    duration: '4-6 hours',
    rating: 4.8,
    reviews: 150,
    emoji: '🏝',
    description: 'A small uninhabited island with crystal clear water and a coconut plantation.',
    tips: ['Great for snorkeling and camping', 'Bring your own supplies'],
    bestFor: ['Adventure Seekers'],
    imageUrl: 'https://images.unsplash.com/photo-1516641295413-435fa52cc596?auto=format&fit=crop&q=80&w=800',
    latitude: -2.38,
    longitude: 106.3
  },
  {
    id: 'tanjung-kerasak',
    name: 'Pantai Tanjung Kerasak',
    location: 'Toboali, South Bangka',
    region: 'Bangka Island',
    subLocation: 'South Bangka',
    categories: ['Beach', 'Nature'],
    entryFee: 'Rp 5,000',
    priceValue: 5000,
    duration: '2 hours',
    rating: 4.6,
    reviews: 280,
    emoji: '🌊',
    description: 'Pristine beach with white sand and large granite rocks at the edge of South Bangka.',
    tips: ['Breathtaking views at high tide', 'Excellent for relaxing'],
    bestFor: ['Families', 'Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    latitude: -3.1,
    longitude: 106.5
  },
  {
    id: 'pineapple-monument',
    name: 'Tugu Nanas Toboali',
    location: 'Toboali, South Bangka',
    region: 'Bangka Island',
    subLocation: 'South Bangka',
    categories: ['Photo Spot'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '30 min',
    rating: 4.1,
    reviews: 150,
    emoji: '🍍',
    description: 'Iconic monument in the shape of a pineapple, representing the local fruit of Toboali.',
    tips: ['Quick photo stop when in town'],
    bestFor: ['Solo'],
    imageUrl: 'https://images.unsplash.com/photo-1550258114-68bd6a1663a7?auto=format&fit=crop&q=80&w=800',
    latitude: -3.01,
    longitude: 106.44
  },
  {
    id: 'pantai-nyiur-melambai',
    name: 'Pantai Nyiur Melambai',
    location: 'Manggar, East Belitung',
    region: 'Belitung Island',
    subLocation: 'East Belitung',
    categories: ['Beach'],
    entryFee: 'Free',
    priceValue: 0,
    duration: '2 hours',
    rating: 4.4,
    reviews: 950,
    emoji: '🌴',
    description: 'Beach lined with pine and coconut trees. Very popular local spot.',
    tips: ['Try the street food stalls', 'Relaxing sea breeze'],
    bestFor: ['Families'],
    imageUrl: 'https://images.unsplash.com/photo-1520483601560-389dff434f1c?auto=format&fit=crop&q=80&w=800',
    latitude: -2.89,
    longitude: 108.28
  },
  {
    id: 'kedai-kopi-adoe-2',
    name: 'Kedai Kopi Roemah Adoe',
    location: 'Pangkalpinang',
    region: 'Bangka Island',
    subLocation: 'Pangkalpinang',
    categories: ['Cafe'],
    entryFee: 'Rp 30,000–70,000',
    priceValue: 50000,
    duration: '1.5 hours',
    rating: 4.6,
    reviews: 240,
    emoji: '☕',
    description: 'Modern cafe with vintage house vibes. Great food and coffee.',
    tips: ['Try their signature local blends'],
    bestFor: ['Solo', 'Couples'],
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=800',
    latitude: -2.13,
    longitude: 106.12
  }
];

export const TEMPLATES: Template[] = [
  {
    id: '100k-challenge',
    name: 'Rp 100K Date Challenge',
    category: 'Budget',
    isPremium: false,
    destinationCount: 4,
    duration: '8 hours',
    region: 'Bangka Island',
    budgetRange: 'Rp 75,000–100,000 / person',
    description: 'Bangka best experiences are free — good food, real culture, and stunning nature under Rp 100K.',
    emoji: '🌊',
    items: [
      { time: '07:30', destinationId: 'tiam-o-ie', duration: '1h' },
      { time: '09:00', destinationId: 'danau-kaolin', duration: '1.5h' },
      { time: '11:00', destinationId: 'matras', duration: '2h' },
      { time: '13:00', destinationId: 'lempah-kuning-pak-hamid', duration: '1h' }
    ]
  },
  {
    id: 'romantic-morning',
    name: 'Morning Beach Date',
    category: 'Romantic',
    isPremium: false,
    destinationCount: 3,
    duration: '5 hours',
    region: 'Belitung Island',
    budgetRange: 'Rp 50,000–80,000 / person',
    description: 'Golden-hour light on famous boulders, intimate kopitiam breakfast.',
    emoji: '☀',
    items: [
      { time: '06:00', destinationId: 'tanjung-tinggi', duration: '2.5h' },
      { time: '09:00', destinationId: 'kong-djie', duration: '1.5h' },
      { time: '11:00', destinationId: 'batu-bedil', duration: '1h' }
    ]
  },
  {
    id: 'premium-sunset',
    name: 'Sunset Date Romantis',
    category: 'Romantic',
    isPremium: true,
    destinationCount: 4,
    duration: '8 hours',
    region: 'Belitung Island',
    budgetRange: 'Rp 200,000–350,000 / person',
    description: 'Curated romantic day ending with private sunset dinner setup.',
    emoji: '🌹',
    items: [
      { time: '14:00', destinationId: 'bongs-coffee', duration: '1.5h' },
      { time: '16:00', destinationId: 'tanjung-kelayang', duration: '2h' },
      { time: '18:15', destinationId: 'burung-mandi-sunset', duration: '1.5h' }
    ]
  },
  {
    id: 'artsy-belitung',
    name: 'Artsy Belitung Walk',
    category: 'Artsy',
    isPremium: false,
    destinationCount: 3,
    duration: '4 hours',
    region: 'Belitung Timur',
    budgetRange: 'Rp 40,000–70,000 / person',
    description: 'Literary trails and rainbows. A colorful journey through Laskar Pelangi locations.',
    emoji: '🎨',
    items: [
      { time: '09:00', destinationId: 'replika-sekolah', duration: '1h' },
      { time: '10:30', destinationId: 'museum-kata', duration: '1.5h' },
      { time: '12:30', destinationId: 'gangan-bu-ijah', duration: '1h' }
    ]
  },
  {
    id: 'active-bangka',
    name: 'Active Nature Bangka',
    category: 'Adventure',
    isPremium: false,
    destinationCount: 3,
    duration: '6 hours',
    region: 'Bangka Island',
    budgetRange: 'Rp 60,000–120,000 / person',
    description: 'Boulders, blue lakes, and coastal hikes for the active soul.',
    emoji: '🧗',
    items: [
      { time: '14:00', destinationId: 'parai-tenggiri', duration: '2h' },
      { time: '16:30', destinationId: 'danau-kaolin', duration: '1.5h' },
      { time: '18:30', destinationId: 'martabak-har', duration: '1h' }
    ]
  },
  {
    id: 'chill-cafe-hop',
    name: 'Island Cafe Ritual',
    category: 'Relaxing',
    isPremium: true,
    destinationCount: 3,
    duration: '5 hours',
    region: 'Belitung Island',
    budgetRange: 'Rp 150,000–250,000 / person',
    description: 'Slow living in the heart of Tanjung Pandan. The finest beans and local treats.',
    emoji: '🥐',
    items: [
      { time: '09:00', destinationId: 'kong-djie', duration: '1.5h' },
      { time: '11:00', destinationId: 'bongs-coffee', duration: '1.5h' },
      { time: '13:00', destinationId: 'roaster-belitung', duration: '1.5h' }
    ]
  }
];
